AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-processing

  Sample SAM Template for image-processing

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Resources:
  ImageProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        SendFilesApiEvent:
          Type: Api
          Properties:
            Method: put
            Path: /send-files/{bucket}/{object}
            RestApiId: !Ref ImageProcessingApi
        S3TriggerEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageProcessingS3BucketForImages
            Events: s3:ObjectCreated:*
  ImageProcessingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors: "'*'"
      BinaryMediaTypes:
      - "*~1*"
  ImageProcessingS3BucketForWebsite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: image-processing-s3-website
      Tags:
        - Key: Project
          Value: image-processing
  ImageProcessingS3BucketForImages:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: image-processing-s3-storage-images
      Tags:
        - Key: Project
          Value: image-processing
  ImageProcessingS3BucketForMetadata:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: image-processing-s3-storage-metadata
      Tags:
        - Key: Project
          Value: image-processing
  ApiS3PutObjectsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: "APIUploadFilesToS3Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                  - "logs:PutLogEvents"
                  - "logs:GetLogEvents"
                  - "logs:FilterLogEvents"
                  - "s3:PutObject"
                Resource: !Ref ImageProcessingApi

