AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-processing

  Sample SAM Template for image-processing

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Resources:
  ImageProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        ProcessImage:
          Type: Api
          Properties:
            Path: /process
            Method: post
  ImagesMetadataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: image-processing-table-metadata
      PrimaryKey:
        Name: GeneratedImageId
        Type: String
      Tags:
        Project: image-processing
  ImageProcessingS3BucketForImages:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: image-processing-s3-storage-images
      Tags:
        - Key: Project
          Value: image-processing
  ImageProcessingS3BucketForMetadata:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: image-processing-s3-storage-metadata
      Tags:
        - Key: Project
          Value: image-processing
